import {Metacritic_platforms} from "@/src/app/modules/gameModules/GameDetailsModules/IMetacritic";
import {Ratings} from "@/src/app/modules/gameModules/GameDetailsModules/IRatings";
import {Reactions} from "@/src/app/modules/gameModules/GameDetailsModules/IReactions";
import {Added_by_status} from "@/src/app/modules/gameModules/GameDetailsModules/IAdded_by_status";
import {Parent_platforms} from "@/src/app/modules/gameModules/GameDetailsModules/IParentPlatform";
import {Platforms} from "@/src/app/modules/gameModules/GameDetailsModules/IPlatformDetails";
import {Stores} from "@/src/app/modules/gameModules/GameDetailsModules/IStores";
import {Developers} from "@/src/app/modules/gameModules/GameDetailsModules/IDevelopers";
import {Genres} from "@/src/app/modules/gameModules/GameDetailsModules/IGenres";
import {Tags} from "@/src/app/modules/gameModules/GameDetailsModules/ITags";
import {Publishers} from "@/src/app/modules/gameModules/GameDetailsModules/IPublishers";
import {Esrb_rating} from "@/src/app/modules/gameModules/GameDetailsModules/IEsrb_rating";


export interface IGameDetails {
  id: number;
  slug: string;
  name: string;
  name_original: string;
  description: string;
  metacritic: number | null;
  metacritic_platforms: Metacritic_platforms[];
  released: string;
  tba: boolean;
  updated: string;
  background_image: string;
  background_image_additional: string;
  website: string;
  rating: number;
  rating_top: number;
  ratings: Ratings[];
  reactions: Reactions;
  added: number;
  added_by_status: Added_by_status;
  playtime: number;
  screenshots_count: number;
  movies_count: number;
  creators_count: number;
  achievements_count: number;
  parent_achievements_count: number;
  reddit_url: string;
  reddit_name: string;
  reddit_description: string;
  reddit_logo: string;
  reddit_count: number;
  twitch_count: number;
  youtube_count: number;
  reviews_text_count: number;
  ratings_count: number;
  suggestions_count: number;
  alternative_names: string[];
  metacritic_url: string;
  parents_count: number;
  additions_count: number;
  game_series_count: number;
  user_game?: string;
  reviews_count: number;
  saturated_color: string;
  dominant_color: string;
  parent_platforms: Parent_platforms[];
  platforms: Platforms[];
  stores: Stores[];
  developers: Developers[];
  genres: Genres[];
  tags: Tags[];
  publishers: Publishers[];
  esrb_rating: Esrb_rating | null;
  clip?: string;
  description_raw: string;
}